name: snapmind
description: Turn waiting time into something — Quiz & Puzzle micro-games.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Game engine (pour les puzzles)
  flame: ^1.18.0

  # Navigation
  # go_router: ^13.2.0   # optionnel si tu préfères Navigator classique

  # UI
  google_fonts: ^6.2.1

  # (Optionnel) Database
  # supabase_flutter: ^2.5.0

flutter:
  uses-material-design: true

  # Pour ajouter la police Poppins localement si pas de google_fonts :
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-ExtraBold.ttf
  #         weight: 800